services:
  - type: web
    name: image-processing-system
    env: node
    buildCommand: npm install
    startCommand: node src/app.js
    envVars:
      - key: MONGODB_URI
        value: your_mongodb_uri
      - key: PORT
        value: 10000
